/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Product,
} from './components/product/product';

export namespace Components {
  interface ConnectModalHeader {
    'header': string;
  }
  interface DdHost {}
  interface ModalPage {
    'component': string;
    'payload': any;
  }
  interface ProductList {
    'label'?: string;
    'list': Product;
  }
}

declare global {


  interface HTMLConnectModalHeaderElement extends Components.ConnectModalHeader, HTMLStencilElement {}
  var HTMLConnectModalHeaderElement: {
    prototype: HTMLConnectModalHeaderElement;
    new (): HTMLConnectModalHeaderElement;
  };

  interface HTMLDdHostElement extends Components.DdHost, HTMLStencilElement {}
  var HTMLDdHostElement: {
    prototype: HTMLDdHostElement;
    new (): HTMLDdHostElement;
  };

  interface HTMLModalPageElement extends Components.ModalPage, HTMLStencilElement {}
  var HTMLModalPageElement: {
    prototype: HTMLModalPageElement;
    new (): HTMLModalPageElement;
  };

  interface HTMLProductListElement extends Components.ProductList, HTMLStencilElement {}
  var HTMLProductListElement: {
    prototype: HTMLProductListElement;
    new (): HTMLProductListElement;
  };
  interface HTMLElementTagNameMap {
    'connect-modal-header': HTMLConnectModalHeaderElement;
    'dd-host': HTMLDdHostElement;
    'modal-page': HTMLModalPageElement;
    'product-list': HTMLProductListElement;
  }
}

declare namespace LocalJSX {
  interface ConnectModalHeader {
    'header'?: string;
  }
  interface DdHost {}
  interface ModalPage {
    'component'?: string;
    'payload'?: any;
  }
  interface ProductList {
    'label'?: string;
    'list'?: Product;
  }

  interface IntrinsicElements {
    'connect-modal-header': ConnectModalHeader;
    'dd-host': DdHost;
    'modal-page': ModalPage;
    'product-list': ProductList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'connect-modal-header': LocalJSX.ConnectModalHeader & JSXBase.HTMLAttributes<HTMLConnectModalHeaderElement>;
      'dd-host': LocalJSX.DdHost & JSXBase.HTMLAttributes<HTMLDdHostElement>;
      'modal-page': LocalJSX.ModalPage & JSXBase.HTMLAttributes<HTMLModalPageElement>;
      'product-list': LocalJSX.ProductList & JSXBase.HTMLAttributes<HTMLProductListElement>;
    }
  }
}
